FROM bitnami/moodle:3.11.6

RUN apt-get update
RUN apt-get install xz-utils
RUN apt-get -y install curl

RUN curl -fsSL https://deb.nodesource.com/setup_19.x | bash - &&\
   apt-get install -y nodejs

RUN npm install -g npm@9.6.5

RUN npm install -g localtunnel

RUN npm fund

# Confirmar la instalación
RUN node --version
RUN npm --version

# Redireccionar del puerto 8080 a tnmmoodle.loca.lt en la web
RUN echo "* * * * * root /bin/bash -c 'lt -p 8080 -s tnmmoodle'" >> /etc/crontab