version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "--silent"]
    restart: always
  moodle:
    image: bitnami/moodle:3.11.6
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - PHP_POST_MAX_SIZE=3G
      - PHP_UPLOAD_MAX_FILESIZE=3G 
      - PHP_MEMORY_LIMIT=3G

    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
  apimoodle:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mariadb
      - DB_NAME=bitnami_moodle
      - DB_USER=bn_moodle
      - ALLOW_EMPTY_PASSWORD=yes
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./api:/app

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local
  moodledata_data:
    driver: local