openapi: 3.0.0
info:
  title: MOODLE API
  version: 1.0.0
tags:
  - name: API
    description: Documentacion de la API de Moodle
paths:
  /insertar-mensaje:
    put:
      tags:
        - API
      summary: Insertar un mensaje en el foro
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                discussion:
                  type: string
                  description: ID de discusión del foro
                userId:
                  type: string
                  description: ID de usuario
                msg:
                  type: string
                  description: Contenido del mensaje
                subject:
                  type: string
                  description: Asunto del mensaje
              required:
                - discussion
                - userId
                - msg
                - subject
      responses:
        "200":
          description: El mensaje se insertó correctamente
        "400":
          description: Error al procesar la solicitud
  /obtener-foros:
    get:
      tags:
        - API
      summary: Obtener la lista de foros
      responses:
        "200":
          description: Lista de foros
          content:
            application/json:
              example: |
                [
                  {
                    "id": 1,
                    "course": "Curso 1",
                    "name": "Foro 1"
                  },
                  {
                    "id": 2,
                    "course": "Curso 2",
                    "name": "Foro 2"
                  }
                ]
  /obtener-discusiones:
    get:
      tags:
        - API
      summary: Obtener discusiones
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID de la discusión
                    course:
                      type: string
                      description: Curso de la discusión
                    forum:
                      type: string
                      description: Foro de la discusión
                    name:
                      type: string
                      description: Nombre de la discusión
    parameters: []
  /obtener-quizzes/course={course}:
    get:
      tags:
        - API
      summary: Obtener quizzes por curso
      parameters:
        - in: path
          name: course
          schema:
            type: integer
          required: true
          description: El identificador del curso del cual se obtendrán los quizzes.
      responses:
        "200":
          description: Lista de quizzes obtenidos exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: El identificador del quiz.
                    course:
                      type: integer
                      description: El identificador del curso al que pertenece el quiz.
                    name:
                      type: string
                      description: El nombre del quiz.
                    intro:
                      type: string
                      description: La introducción del quiz.
  /obtener-mensajes-discusion/{discussion}:
    get:
      tags:
        - API
      summary: Obtener mensajes de una discusión en el foro
      parameters:
        - in: path
          name: discussion
          schema:
            type: string
          required: true
          description: El identificador de la discusión de la cual se obtendrán los mensajes.
      responses:
        "200":
          description: Lista de mensajes obtenidos exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: El identificador del mensaje.
                    discussion:
                      type: string
                      description: El identificador de la discusión a la cual pertenece el mensaje.
                    parent:
                      type: integer
                      description: El identificador del mensaje padre (si existe).
                    userId:
                      type: integer
                      description: El identificador del usuario que creó el mensaje.
                    created:
                      type: string
                      format: date-time
                      description: La fecha y hora de creación del mensaje.
                    subject:
                      type: string
                      description: El asunto del mensaje.
                    message:
                      type: string
                      description: El contenido del mensaje.
  /obtener-datos-foro/name={name}:
    get:
      tags:
        - API
      summary: Obtener datos de un foro por nombre
      parameters:
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: El nombre del foro del cual se obtendrán los datos.
      responses:
        "200":
          description: Datos del foro obtenidos exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: El identificador del foro.
                    course:
                      type: integer
                      description: El identificador del curso al que pertenece el foro.
                    intro:
                      type: string
                      description: La introducción del foro.
  /user-login:
    put:
      tags:
        - API
      summary: Iniciar sesión de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Nombre de usuario
                password:
                  type: string
                  description: Contraseña
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: ID del usuario
                    username:
                      type: string
                      description: Nombre de usuario
                    firstname:
                      type: string
                      description: Nombre del usuario
                    lastname:
                      type: string
                      description: Apellido del usuario
                    email:
                      type: string
                      description: Correo electrónico del usuario
        "400":
          description: Bad Request
  /obtener-nombre-discusion/id={id}:
    get:
      tags:
        - API
      summary: Obtener nombre de una discusión por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El identificador de la discusión de la cual se desea obtener el nombre.
      responses:
        "200":
          description: Nombre de la discusión obtenido exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: El nombre de la discusión.
  /obtener-participantes-curso/id={courseId}:
    get:
      tags:
        - API
      summary: Obtener participantes de un curso por ID
      parameters:
        - in: path
          name: courseId
          schema:
            type: integer
          required: true
          description: El identificador del curso del cual se desea obtener los participantes.
      responses:
        "200":
          description: Lista de participantes obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: integer
                      description: El identificador del participante.
  /obtener-preguntas-examen/id={id}:
    get:
      tags:
        - API
      summary: Obtener preguntas de un examen por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El identificador del examen del cual se desean obtener las preguntas.
      responses:
        "200":
          description: Lista de preguntas del examen obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: El identificador del examen.
                    course:
                      type: integer
                      description: El identificador del curso al que pertenece el examen.
                    name:
                      type: string
                      description: El nombre del examen.
                    timelimit:
                      type: string
                      description: El límite de tiempo del examen.
                    intro:
                      type: string
                      description: La introducción del examen.
                    sumgrades:
                      type: number
                      description: La suma de las calificaciones del examen.
                    grade:
                      type: number
                      description: La calificación del examen.
                    quizid:
                      type: integer
                      description: El identificador del cuestionario.
                    questionid:
                      type: integer
                      description: El identificador de la pregunta.
                    question_name:
                      type: string
                      description: El nombre de la pregunta.
                    question_text:
                      type: string
                      description: El texto de la pregunta.
                    defaultmark:
                      type: number
                      description: La calificación predeterminada de la pregunta.
                    question_answer_id:
                      type: integer
                      description: El identificador de la respuesta de la pregunta.
                    question_answer:
                      type: string
                      description: La respuesta de la pregunta.
                    fraction:
                      type: number
                      description: La fracción de la calificación de la pregunta.
                    fullName:
                      type: string
                      description: El nombre completo del curso.
                    shortName:
                      type: string
                      description: El nombre corto del curso.
                    summary:
                      type: string
                      description: El resumen del curso.
                    feedback:
                      type: string
                      description: El comentario sobre la respuesta del usuario.
                    generalfeedback:
                      type: string
                      description: El comentario general sobre la pregunta.
  /insertar-intento-quiz:
    put:
      tags:
        - API
      summary: Insertar intento de examen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quiz:
                  type: string
                  description: Examen
                userid:
                  type: string
                  description: ID de usuario
                layout:
                  type: string
                  description: Diseño
                timestart:
                  type: string
                  description: Hora de inicio
                timefinish:
                  type: string
                  description: Hora de finalización
                sumgrades:
                  type: string
                  description: Suma de las calificaciones
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /insertar-intento-lesson:
    put:
      tags:
        - API
      summary: Insertar intento de lección
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lessonId:
                  type: string
                  description: ID de la lección
                pageId:
                  type: string
                  description: ID de la página
                userid:
                  type: string
                  description: ID de usuario
                answerId:
                  type: string
                  description: ID de la respuesta
                correct:
                  type: string
                  description: Correcto
                userAnswer:
                  type: string
                  description: Respuesta del usuario
                timeSeen:
                  type: string
                  description: Tiempo visto
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
  /obtener-leccion/id={id}:
    get:
      tags:
        - API
      summary: Obtener respuestas de una lección por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El identificador de la lección de la cual se desean obtener las respuestas.
      responses:
        "200":
          description: Lista de respuestas de la lección obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    pageId:
                      type: integer
                      description: El identificador de la página de la lección.
                    prevPageId:
                      type: integer
                      description: El identificador de la página anterior.
                    nextPageId:
                      type: integer
                      description: El identificador de la página siguiente.
                    qType:
                      type: string
                      description: El tipo de pregunta.
                    contents:
                      type: string
                      description: El contenido de la página.
                    answerId:
                      type: integer
                      description: El identificador de la respuesta.
                    jumpTo:
                      type: string
                      description: La página a la que se debe saltar.
                    score:
                      type: integer
                      description: La puntuación de la respuesta.
                    answer:
                      type: string
                      description: La respuesta.
                    response:
                      type: string
                      description: La respuesta del usuario.
  /obtener-videos/course={course}:
    get:
      tags:
        - API
      summary: Obtener videos de un curso por ID
      parameters:
        - in: path
          name: course
          schema:
            type: integer
          required: true
          description: El identificador del curso del cual se desean obtener los videos.
      responses:
        "200":
          description: Lista de videos del curso obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: El nombre del video.
                    externalurl:
                      type: string
                      description: La URL externa del video.
  /obtener-pdf/course={course}:
    get:
      tags:
        - API
      summary: Obtener PDFs de un curso por ID
      parameters:
        - in: path
          name: course
          schema:
            type: integer
          required: true
          description: El identificador del curso del cual se desean obtener los PDFs.
      responses:
        "200":
          description: Lista de PDFs del curso obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      description: El nombre del PDF.
                    externalurl:
                      type: string
                      description: La URL externa del PDF.
  /obtener-cursos:
    get:
      summary: Obtener cursos
      responses:
        "200":
          description: Lista de cursos obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: El identificador del curso.
                    fullname:
                      type: string
                      description: El nombre completo del curso.
