FROM python:3.10-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y xz-utils wget build-essential libmariadb-dev

RUN wget https://downloads.mariadb.com/Connectors/c/connector-c-3.3.2/mariadb-connector-c-3.3.2-debian-bullseye-amd64.tar.gz \
    && tar xvf mariadb-connector-c-3.3.2-debian-bullseye-amd64.tar.gz \
    && cd mariadb-connector-c-3.3.2-debian-bullseye-amd64 \
    && cp -R bin/ /usr/local/ \
    && cp -R lib/ /usr/local/ \
    && cp -R include/ /usr/local/ \
    && ldconfig

RUN pip install --upgrade pip

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

CMD ["python", "api.py"]
